parent=base
import=common/keycloak

styles=css/kube-center.css
scripts=js/split-layout.js
kcButtonClass=kc-button
kcButtonPrimaryClass=kc-button-primary
kcButtonDefaultClass=kc-button-default
kcButtonLargeClass=kc-button-large
kcInputClass=kc-input
kcFormGroupClass=kc-form-group
